GET /itemdeleilao HTTP/1.1
Host: localhost:8080
Content-Type: application/json

POST /itemdeleilao HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "nome": "Cadeira",
  "valorMinimo": 100,
  "leilaoAberto": true
}

PUT /itemdeleilao/2 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "nome": "Cadeira de madeira",
  "valorMinimo": 100,
  "leilaoAberto": true
}

POST /itemdeleilao/1 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "valor": 400,
  "participante": {
    "id": 1
  }
}

POST /participante HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "nome": "Edson Angoti Júnior",
  "cpf": "123.456.789-00"
}


